import type { Metadata } from "next";
import { Geist, Geist_Mono ,IBM_Plex_Serif} from "next/font/google";
import "./globals.css";

const ibmPlexSerif= IBM_Plex_Serif(
  {
    variable:'--font-ibm-plex-serif',
    subsets:['latin'],
    weight:['400','500','600','700'],
    display:'swap'
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
